spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db1?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 666666

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
